###update categories
PUT  http://localhost:8080/categories/1 HTTP/1.1
content-type: application/json

  {
    "name":"Drinks"
  }

###create categories
POST http://localhost:8080/categories HTTP/1.1
content-type: application/json

  {
    "name":"Foods"
  }

###Delete categories
DELETE  http://localhost:8080/categories/10000
###get all categories
GET http://localhost:8080/categories?page=0&size=12&sort=name,asc

###get categories by id
GET http://localhost:8080/categories/3

###get all products
GET http://localhost:8080/products?page=0&size=12&sort=name,asc



###get products by id
GET http://localhost:8080/products/2

###Delete products
DELETE  http://localhost:8080/products/2000


###
##Create product
POST http://localhost:8080/products HTTP/1.1
content-type: application/json

  {
    "name":"PS52017",
    "description":"The new generate PS5",
    "imgUrl":"",
    "price":600.0,
    "date":"2023-08-25T00:00:00Z",
    "categories":[
      {
        "id":2
      },
      {
        "id":3
      }
    ]
  }

###update products
PUT  http://localhost:8080/products/2 HTTP/1.1
content-type: application/json
  {
    "name":"PS5",
    "description":"The new generate PS5",
    "imgUrl":"",
    "price":600.0,
    "date":"2023-08-25T00:00:00Z",
    "categories":[
      {
        "id":2
      },
      {
        "id":3
      }
    ]
  }

### get all users
GET http://localhost:8080/users?page=0&size=12&sort=firstName,asc

###get users by id
GET http://localhost:8080/users/2

###delete users by id
DELETE http://localhost:8080/users/

###Create user
POST http://localhost:8080/users HTTP/1.1
content-type: application/json

  {
    "firstName":"Bruno",
    "lastName":"Souza",
    "email":"bvaleiro@gmail.com",
    "password":"aeioub",
    "roles":[
      {
        "id":1
      },
      {
        "id":2
      }
    ]
  }
###update user
PUT http://localhost:8080/users/3 HTTP/1.1
content-type: application/json

  {
    "firstName":"Bruno",
    "lastName":"Souza Valeiro",
    "email":"bvaleiro@gmail.com",
    "password":"aeioub",
    "roles":[
      {
        "id":1
      },
      {
        "id":2
      }
    ]
  }